indent = 2
margin = 100
whitespace_ops_in_indices = true
remove_extra_newlines = true
whitespace_typedefs = true
normalize_line_endings = "unix"
pipe_to_function_call = true
whitespace_in_kwargs = true
format_docstrings = true
always_for_in = true
for_in_replacement = "∈"
